### ISSUE TITLE
Error while running CloneFinderPlus

### ISSUE THREAD

**Issue by jmfa** [SayakaMiura/CloneFinderPlus#1]
Hi, 

I'm trying to run the tool with the example toyset but I get the following error:

```
$ python Bootstrap_CloneFinderPlus.py ./Example/ReadCount.txt NA 100
NA not found
Generate clone prediction
Traceback (most recent call last):
  File "/Users/dxjalves/Desktop/2023/2023-CloneFinderPlus/CloneFinderPlus/CloneFinderPlus/RunCloneFinder.py", line 34, in <module>
    os.rename(os.path.join(Dir,CFin), os.path.join(Dir5,CFin))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dxjalves/Desktop/2023/2023-CloneFinderPlus/CloneFinderPlusFullData.txt' -> '/Users/dxjalves/Desktop/2023/2023-CloneFinderPlus/CloneFinderPlusFullData.txt'
python RunCloneFinder.py /Users/dxjalves/Desktop/2023/2023-CloneFinderPlus/CloneFinderPlus\FullData.txt NA
******************NA
/Users/dxjalves/Desktop/2023/2023-CloneFinderPlus/CloneFinderPlus/CloneFinderPlus
ClonePrediction	yes

generate bootstrap replicates
100
generate inference on each bootstrap replicates
Traceback (most recent call last):
  File "/Users/dxjalves/Desktop/2023/2023-CloneFinderPlus/CloneFinderPlus/Bootstrap_CloneFinderPlus.py", line 112, in <module>
    BooG.sample_read_1rep(Wdir+'\\FullData.txt',Boo)			
  File "/Users/dxjalves/Desktop/2023/2023-CloneFinderPlus/CloneFinderPlus/resample/generate_replicate.py", line 326, in sample_read_1rep
    SampOrder, Samp2FreqIn	,SNVnum,Samp2TotRead=self.ObsFreqTaHead(CFin)
  File "/Users/dxjalves/Desktop/2023/2023-CloneFinderPlus/CloneFinderPlus/resample/generate_replicate.py", line 204, in ObsFreqTaHead
    Freq=open(Freq,'r').readlines() 
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dxjalves/Desktop/2023/2023-CloneFinderPlus/CloneFinderPlus\\FullData.txt'```

The command does indeed generate a file called FullData.txt but it stops there.
Any ideas of what might be causing this issue?

Thanks in advance,
J

**Comment by SayakaMiura** [comment]
Are you using Windows? It may not run on Mac or Linux.
